spring.application.name=CONFIG-SERVER

server.port = 9095

spring.cloud.config.server.git.uri = https://github.com/Shahid-1102/ConfigApp.git
spring.cloud.config.server.git.username = Shahid-1102
spring.cloud.config.server.git.password = github@1102
spring.cloud.config.server.git.default = main
