spring.application.name=04ConfgPropertiesWithCollectionsEx

my.app.empId=1001
my.app.name=vamsi
my.app.Salary=20000
my.app.branch[0]=cse
my.app.sport[0]=football
my.app.studentcolour[0]=Red
my.app.section[0]=2
my.app.flag.studentcolor=Red
my.app.PropName.sport=boxing

my.app.V.id=1002
my.app.V.Vname=sai
my.app.V.products[0]=bag
my.app.V.products[1]=bottle





